{% set name = "py3Dmol" %}
{% set version = "2.5.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | lower }}-{{ version }}.tar.gz
  sha256: cb102cc3370800a9ca7679774759f008e34a0f3a283778d85b0410849d370298

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - ipython

test:
  requires:
    - python {{ python_min }}
  imports:
    - py3Dmol

about:
  home: https://github.com/3dmol/3Dmol.js/tree/master/py3Dmol
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Jupyter widget to embed an interactive 3Dmol.js viewer in a notebook

extra:
  recipe-maintainers:
    - mcs07
    - RMeli
