{% set name = "py3Dmol" %}
{% set version = "2.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 07909c587ba7e40d17e2ca9383193ead807af834f9569b108cff784ec4cfb525

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - ipython

test:
  imports:
    - py3Dmol

about:
  home: https://github.com/3dmol/3Dmol.js/tree/master/py3Dmol
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Jupyter widget to embed an interactive 3Dmol.js viewer in a notebook

extra:
  recipe-maintainers:
    - mcs07
    - RMeli
